SistemaTareas/Controllers/TareasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaTareas.Models;
namespace SistemaTareas.Controllers
{
    public class TareasController : Controller
    {
        // GET: Tareas
        public ActionResult Index()
        {
            List<TareaCLS> listaTareas = new List<TareaCLS>();
            try
            {
                ListarCombos();

                using (var bd = new TareasDBEntities())
                {
                    listaTareas = (from tarea in bd.Tareas
                                   join Cat in bd.Categoria
                                   on tarea.IdCategoria equals Cat.IdCategoria
                                   join Est in bd.Estado
                                   on tarea.IdEstado equals Est.IdEstado
                                   join Niv in bd.NivelUrgencia
                                   on tarea.IdNivelUrgencia equals Niv.IdNUrgencia
                                   where tarea.Habilitada == true
                                   select new TareaCLS
                                   {
                                       IdTarea = tarea.IdTarea,
                                       tituloTarea = tarea.TituloTarea,
                                       descripcionTarea = tarea.Descripcion,
                                       fechaInicio = (DateTime)tarea.FechaInicio,
                                       fechaTermino = (DateTime)tarea.FechaTermino,
                                       IdCategoria = tarea.IdCategoria,
                                       IdEstado = tarea.IdEstado,
                                       IdNivelUrgencia = tarea.IdNivelUrgencia,
                                       categoria = Cat.NombreCategoria,
                                       estado = Est.Estado1,
                                       nivelUrgencia = Niv.NivelUrgencia1


                                   }).ToList();
                }

            }
            catch (Exception ex)
            {
                throw new Exception("Mensaje.", ex);
            }

            return View(listaTareas);
        }

       
        public void ListarEstados()
        {
            List<SelectListItem> listarEstados = null;

            using (var bd = new TareasDBEntities())
            {
                listarEstados = (from estados in bd.Estado
                               select new SelectListItem
                               {
                                   Value= estados.IdEstado.ToString(),
                                   Text = estados.Estado1
                               }).ToList();
                listarEstados.Insert(0, new SelectListItem { Text = "-- Seleccione un estado --", Value = "" });
                ViewBag.listarEstados = listarEstados;
            }

        }


        
        public void ListarCategorias()
        {

            List<SelectListItem> listarCategorias = null;
            using (var bd = new TareasDBEntities())
            {
                listarCategorias = (from item in bd.Categoria
                         select new SelectListItem
                         {
                             Value = item.IdCategoria.ToString(),
                             Text = item.NombreCategoria
                         }).ToList();
                listarCategorias.Insert(0, new SelectListItem { Text = "Seleccione una categoria", Value = "" });
                ViewBag.listarCategorias = listarCategorias;
            }

        }

       
        public void ListarNivelUrgencia()
        {
            List<SelectListItem> listarNivelUrgencia = null;
            using (var bd = new TareasDBEntities())
            {
                listarNivelUrgencia = (from item in bd.NivelUrgencia
                         select new SelectListItem
                         {
                             Value = item.IdNUrgencia.ToString(),
                             Text = item.NivelUrgencia1
                         }).ToList();
                listarNivelUrgencia.Insert(0, new SelectListItem { Text = "Seleccione el nivel de urgencia", Value = "" });
                ViewBag.ListarNivelUrgencia = listarNivelUrgencia;
            }

        }

        public void ListarCombos()
        {
            ListarEstados();
            ListarCategorias();
            ListarNivelUrgencia();
        //    ViewBag.listarCategorias;
        //    ViewBag.listarEstados;
        //    ViewBag.listarNivelUrgencia;
        }

        public ActionResult Agregar()
        {
            ListarCombos();
         

            return View();
        }

        [HttpPost]
        public ActionResult Agregar(TareaCLS oTareasCLS )
        {
            if(!ModelState.IsValid)
            {
                ListarCombos();
                return View(oTareasCLS);
            }
            using (var bd = new TareasDBEntities())
            {
                Tareas oTarea = new Tareas();
                oTarea.TituloTarea = oTareasCLS.tituloTarea;
                oTarea.Descripcion = oTareasCLS.descripcionTarea;
                oTarea.FechaInicio = oTareasCLS.fechaInicio;
                oTarea.FechaTermino = oTareasCLS.fechaTermino;
                oTarea.IdCategoria = oTareasCLS.IdCategoria;
                oTarea.IdEstado = oTareasCLS.IdEstado;
                oTarea.IdNivelUrgencia = oTareasCLS.IdNivelUrgencia;
                oTarea.Habilitada = true;
                bd.Tareas.Add(oTarea);
                bd.SaveChanges();
            }
                return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            ListarCombos();
            TareaCLS tareasCLS = new TareaCLS();

            using (var bd = new TareasDBEntities())
            {
              
                Tareas oTareas = bd.Tareas.Where(p => p.IdTarea.Equals(id)).First();
                tareasCLS.IdTarea = oTareas.IdTarea;
                tareasCLS.tituloTarea = oTareas.TituloTarea;
                tareasCLS.descripcionTarea = oTareas.Descripcion;
                tareasCLS.fechaInicio = oTareas.FechaInicio;
                tareasCLS.fechaTermino =(DateTime)oTareas.FechaTermino;
                tareasCLS.IdCategoria = oTareas.IdCategoria ;
                tareasCLS.IdEstado = oTareas.IdEstado ;
                tareasCLS.IdNivelUrgencia = oTareas.IdNivelUrgencia ;
            }
            return View(tareasCLS);
        }

        [HttpPost]
        public ActionResult Editar(TareaCLS oTareaCLS)
        {
            if (!ModelState.IsValid)
            {
                return View(oTareaCLS);
            }

            int idTarea = oTareaCLS.IdTarea;

            using(var bd = new TareasDBEntities())
            {
                Tareas oTarea = bd.Tareas.Where(p => p.IdTarea.Equals(idTarea)).First();
                oTarea.TituloTarea = oTareaCLS.tituloTarea;
                oTarea.IdTarea  = oTareaCLS.IdTarea;
                oTarea.TituloTarea = oTareaCLS.tituloTarea ;
                oTarea.Descripcion = oTareaCLS.descripcionTarea;
                oTarea.FechaInicio = oTareaCLS.fechaInicio;
                oTarea.FechaTermino =  oTareaCLS.fechaTermino;
                oTarea.IdCategoria = oTareaCLS.IdCategoria;
                oTarea.IdEstado = oTareaCLS.IdEstado;
                oTarea.IdNivelUrgencia = oTareaCLS.IdNivelUrgencia ;
                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        public ActionResult Eliminar(int IdTarea)
        {
            using (var bd = new TareasDBEntities())
            {
                Tareas ot = bd.Tareas.Where(p => p.IdTarea.Equals(IdTarea)).First();
                ot.Habilitada = false;
                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }

   
        public ActionResult listarTodasLasTareas()
        {
            List<TareaCLS> listaTareas = null;
            using (var bd = new TareasDBEntities())
            {
                listaTareas = (from tarea in bd.Tareas
                               join Cat in bd.Categoria
                               on tarea.IdCategoria equals Cat.IdCategoria
                               join Est in bd.Estado
                               on tarea.IdEstado equals Est.IdEstado
                               join Niv in bd.NivelUrgencia
                               on tarea.IdNivelUrgencia equals Niv.IdNUrgencia
                               where tarea.Habilitada == true
                               select new TareaCLS
                               {
                                   IdTarea = tarea.IdTarea,
                                   tituloTarea = tarea.TituloTarea,
                                   descripcionTarea = tarea.Descripcion,
                                   fechaInicio = (DateTime)tarea.FechaInicio,
                                   fechaTermino = (DateTime)tarea.FechaTermino,
                                   categoria = Cat.NombreCategoria,
                                   estado = Est.Estado1,
                                   nivelUrgencia = Niv.NivelUrgencia1
                                 
                               }).ToList();
            }

            return View(listaTareas);
        }

        public ActionResult listarTareasTerminadas()
        {
            List<TareaCLS> listaTareas = null;
            using (var bd = new TareasDBEntities())
            {
                listaTareas = (from tarea in bd.Tareas
                               join Cat in bd.Categoria
                               on tarea.IdCategoria equals Cat.IdCategoria
                               join Est in bd.Estado
                               on tarea.IdEstado equals Est.IdEstado
                               join Niv in bd.NivelUrgencia
                               on tarea.IdNivelUrgencia equals Niv.IdNUrgencia

SistemaTareas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tareas</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand fs-3" href="#"><img src="~/Imagenes/icono.png" height="50" width="50" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="#">@Html.ActionLink("Inicio", "Index", "Tareas", new { area = "" }, new { @class = "nav-link fs-4" })</a>
                    <a class="nav-link" aria-current="page" href="#">@Html.ActionLink("Todas las tareas", "listarTodasLasTareas", "Tareas", new { area = "" }, new { @class = "nav-link fs-4" })</a>
                    <a class="nav-link" aria-current="page" href="#">@Html.ActionLink("Tareas terminadas", "listarTareasTerminadas", "Tareas", new { area = "" }, new { @class = "nav-link fs-4" })</a>
                    <a class="nav-link" aria-current="page" href="#">@Html.ActionLink("Tareas no terminadas", "listarTareasNoTerminadas", "Tareas", new { area = "" }, new { @class = "nav-link fs-4" })</a>

                </div>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()

        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>


    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>

    
</body>
</html>